#create_clock -period 20.000 -name clk [get_ports clk]
set_property PACKAGE_PIN R8 [get_ports pwm_audio_0]
set_property IOSTANDARD LVCMOS33 [get_ports pwm_audio_0]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list system_wrapper_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 12 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {system_wrapper_i/fm_receiver_hardware_0/inst/adc_code[0]} {system_wrapper_i/fm_receiver_hardware_0/inst/adc_code[1]} {system_wrapper_i/fm_receiver_hardware_0/inst/adc_code[2]} {system_wrapper_i/fm_receiver_hardware_0/inst/adc_code[3]} {system_wrapper_i/fm_receiver_hardware_0/inst/adc_code[4]} {system_wrapper_i/fm_receiver_hardware_0/inst/adc_code[5]} {system_wrapper_i/fm_receiver_hardware_0/inst/adc_code[6]} {system_wrapper_i/fm_receiver_hardware_0/inst/adc_code[7]} {system_wrapper_i/fm_receiver_hardware_0/inst/adc_code[8]} {system_wrapper_i/fm_receiver_hardware_0/inst/adc_code[9]} {system_wrapper_i/fm_receiver_hardware_0/inst/adc_code[10]} {system_wrapper_i/fm_receiver_hardware_0/inst/adc_code[11]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 16 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {system_wrapper_i/fm_receiver_hardware_0/inst/audio_out[0]} {system_wrapper_i/fm_receiver_hardware_0/inst/audio_out[1]} {system_wrapper_i/fm_receiver_hardware_0/inst/audio_out[2]} {system_wrapper_i/fm_receiver_hardware_0/inst/audio_out[3]} {system_wrapper_i/fm_receiver_hardware_0/inst/audio_out[4]} {system_wrapper_i/fm_receiver_hardware_0/inst/audio_out[5]} {system_wrapper_i/fm_receiver_hardware_0/inst/audio_out[6]} {system_wrapper_i/fm_receiver_hardware_0/inst/audio_out[7]} {system_wrapper_i/fm_receiver_hardware_0/inst/audio_out[8]} {system_wrapper_i/fm_receiver_hardware_0/inst/audio_out[9]} {system_wrapper_i/fm_receiver_hardware_0/inst/audio_out[10]} {system_wrapper_i/fm_receiver_hardware_0/inst/audio_out[11]} {system_wrapper_i/fm_receiver_hardware_0/inst/audio_out[12]} {system_wrapper_i/fm_receiver_hardware_0/inst/audio_out[13]} {system_wrapper_i/fm_receiver_hardware_0/inst/audio_out[14]} {system_wrapper_i/fm_receiver_hardware_0/inst/audio_out[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list system_wrapper_i/fm_receiver_hardware_0/inst/audio_valid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list system_wrapper_i/fm_receiver_hardware_0/inst/sample_valid]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
